version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - STACK_NAME=${STACK_NAME}
        - ENABLE_FINANCIAL=${ENABLE_FINANCIAL:-false}
        - GERENCIANET_PIX_CERT=${GERENCIANET_PIX_CERT:-production-cert}
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - ENABLE_FINANCIAL=${ENABLE_FINANCIAL:-false}
      - GERENCIANET_SANDBOX=${GERENCIANET_SANDBOX:-false}
      - GERENCIANET_PIX_CERT=${GERENCIANET_PIX_CERT:-production-cert}
      - GERENCIANET_CLIENT_ID=${GERENCIANET_CLIENT_ID}
      - GERENCIANET_CLIENT_SECRET=${GERENCIANET_CLIENT_SECRET}
      - GERENCIANET_PIX_KEY=${GERENCIANET_PIX_KEY}
    env_file:
      - .env
    depends_on:
      - frontend
    networks:
      - app-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.caamg.com.br`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${BACKEND_URL}
        - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=24
        - STACK_NAME=${STACK_NAME}
        - REACT_APP_COLOR=${COLOR}
        - REACT_APP_TAB_NAME=${TAB_NAME}
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=24
      - STACK_NAME=${STACK_NAME}
      - REACT_APP_COLOR=${COLOR}
      - REACT_APP_TAB_NAME=${TAB_NAME}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.caamg.com.br`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3001"

networks:
  app-network:
    driver: bridge
  traefik:
    external: true 